### ISSUE TITLE
dew_about_me_css Homework Assignment -- Issues with Cloning and Pushing!

### ISSUE THREAD

**Issue by ghost** [ga-wdi-exercises/dew_about_me_css#37]
I had issues with both cloning and pushing in git today. I am getting the following error message:
"Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists."
Today is the first time this has happened.

Until I can resolve the issue, here is the code from my styles.css file for the dew_about_me_css homework assignment (comfort level and completeness below):

header {
  display: block;
}

h1 {
  background-color: #a60000;
  color: white;
  text-align: right;
  font: Gringo Sans Narrow Light;
  margin: 0px 1200px 0px 0px;
  padding-left: 10px;
  padding-right: 10px;
  padding-top: 10px;
  padding-bottom: 10px;
}

div.hero {
  padding-top: 200px;
  padding-top: 400px;
  background-image: url("me.jpg");
  background-size: cover;
  background-repeat: no-repeat;
}

section.about {
  background-color: #fff;
  text-align: left;
  padding-left: 400px;
  padding-right: 400px;
  margin: 0 auto;
  font-size: 18px;
  font-family: arial;
}

section.contact {
  color: #ffffff;
  text-decoration: none;
  margin: 0px 400px 0 400px;
  padding-left: 230px;
  padding-right: 400px;
  display: flex;
}

a.contact {
  display: none;
}

footer {
  font-size: 10px;
  text-align: center;
  background: #2C2C2C;
  color: #acacac;
  padding-left: 10px;;
  padding-right: 10px;
  padding-top: 7px;
  padding-bottom: 0.02px;
  margin: 0px 400px 0px 400px;
}

comfort_level: 2
completeness: 3

Sorry about that... Hopefully I can fix this problem before pull requests need to be submitted!

**Comment by RobertAKARobin** [comment]
Ask an instructor today!
