### ISSUE TITLE
Image upload through CSS

### ISSUE THREAD

**Issue by rewarren** [ga-wdi-exercises/dew_about_me_css#47]
Image won't load

.hero {
  background-image: url("me.jpg");
  background-color: #000;
  background-repeat: no-repeat;
  background-position: center;
  width: auto;
  height: 50%;
}

**Comment by RobertAKARobin** [comment]
Your CSS looks fine! My guess is the image is in a different directory. Here's the test: if your HTML page is at `file:///Desktop/index.html`, in your browser go to `file:///Desktop/me.jpg`. If your image shows up, you're in the right place! If not, you probably forgot a `../` or something somewhere.

If THAT doesn't work, it may be a permissions issue. Long story short: click on the image and go to File > Get Info (or hit Command + I), at the bottom click on the padlock, enter your password, and change everything in the "Privilege" column to "Read & Write".
