### ISSUE TITLE
https://github.com/tomBeach/dew_about_me_css

### ISSUE THREAD

**Issue by tomBeach** [ga-wdi-exercises/dew_about_me_css#8]
comfort_level: 1
completeness: 3

Not sure if this is the proper homework submission procedure but the Pull Request option was "grayed out" when I attempted that method...  anyway, here's the link to my forked css ddw_about_me repo

**Comment by adambray** [comment]
@tomBeach I'm gonna close this issue since you figured out how to submit a pull request. We'll use that as your submission instead.

(also, kudos for coming up with this as an alternative!)
